version: '3.8'

services:
  fastapi-engine:
    build: ./ml-service
    container_name: alexandria-fastapi
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

  backend-api:
    build: ./backend
    container_name: alexandria-nestjs
    env_file: .env

    ports:
      - "3001:3001"
    depends_on:
      - fastapi-engine
  frontend-ui:
    build: ./ml-service
    container_name: alexandria-streamlit
    command: ["streamlit", "run", "app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]

    ports:
      - "8501:8501"
    depends_on:
      - backend-api
  seeder:
    build: ./ml-service
    container_name: alexandria-seeder
    command: ["python", "seed.py"]

    profiles: ["tools"]
    depends_on:
      - backend-api
  evaluator:
    build: ./ml-service
    container_name: alexandria-evaluator
    command: ["python", "evaluate.py"]
    
    profiles: ["tools"]
    depends_on:
      - backend-api